#!/bin/bash -l

#SBATCH -M snowy
#SBATCH -A uppmax2023-2-13
#SBATCH -p core -n 32
#SBATCH -t 100:00

module load gcc openmpi
mpirun ./quicksort /proj/uppmax2023-2-13/nobackup/qsort_indata/input2000000000.txt test.txt 1
